// ~/.claude/hooks/lib/recovery-handler.ts
// Recovery Handler — 5-Strategy Escalation Ladder for Error Recovery
// Inspired by aios-core recovery-handler.js
// Created: 2026-02-24

import { existsSync, readFileSync, writeFileSync, mkdirSync, appendFileSync } from 'fs';
import { join, dirname } from 'path';
import { execSync } from 'child_process';
import { homedir } from 'os';

// ==========================================
// Constants
// ==========================================

const HOME = homedir();
const ECOSYSTEM_ROOT = join(HOME, 'copywriting-ecosystem');
const RECOVERY_LOG_FILE = 'recovery-log.yaml';
const MAX_RETRIES = 3;
const MAX_BACKOFF_MS = 30_000;
const CIRCULAR_THRESHOLD = 3;

// ==========================================
// Types
// ==========================================

export type StrategyName = 'RETRY' | 'ROLLBACK' | 'SKIP' | 'ESCALATE' | 'RECOVERY_WORKFLOW';
export type ErrorClass = 'TRANSIENT' | 'PERMANENT';

export interface RecoveryContext {
  error: string;
  tool: string;
  offer_path: string;
  phase: string;
  deliverable?: string;
  attempt_history: AttemptRecord[];
}

export interface AttemptRecord {
  strategy: StrategyName;
  timestamp: string;
  success: boolean;
  details: string;
}

export interface RecoveryResult {
  resolved: boolean;
  strategy_used: string;
  attempts: number;
  action_taken: string;
  should_continue_pipeline: boolean;
}

// ==========================================
// Error Classification
// ==========================================

const TRANSIENT_PATTERNS: RegExp[] = [
  /timeout/i, /ETIMEDOUT/i, /ECONNRESET/i, /ECONNREFUSED/i,
  /rate.?limit/i, /429/i, /503/i, /502/i,
  /mcp.*connection/i, /session.*not.*found/i,
  /EPIPE/i, /socket.*hang.*up/i,
];

const PERMANENT_PATTERNS: RegExp[] = [
  /not.*found/i, /ENOENT/i, /permission.*denied/i, /EACCES/i,
  /invalid.*input/i, /validation.*fail/i, /schema.*error/i,
  /mecanismo.*not.*validated/i, /gate.*blocked/i,
];

export function classifyError(error: string): ErrorClass {
  for (const pattern of PERMANENT_PATTERNS) {
    if (pattern.test(error)) return 'PERMANENT';
  }
  for (const pattern of TRANSIENT_PATTERNS) {
    if (pattern.test(error)) return 'TRANSIENT';
  }
  // Default: treat unknown errors as transient (retry first)
  return 'TRANSIENT';
}

// ==========================================
// Circular Detection
// ==========================================

export function detectCircular(history: AttemptRecord[]): boolean {
  const retries = history.filter((a) => a.strategy === 'RETRY' && !a.success);
  return retries.length >= CIRCULAR_THRESHOLD;
}

// ==========================================
// Recovery Log (Append-Only YAML)
// ==========================================

export function logRecoveryAttempt(offerPath: string, attempt: AttemptRecord & {
  error: string;
  tool: string;
  attempts_total: number;
  resolved: boolean;
  action: string;
}): void {
  const logPath = join(ECOSYSTEM_ROOT, offerPath, RECOVERY_LOG_FILE);
  const logDir = dirname(logPath);

  if (!existsSync(logDir)) {
    mkdirSync(logDir, { recursive: true });
  }

  // Build YAML entry manually (no npm deps)
  const entry = [
    `  - timestamp: "${attempt.timestamp}"`,
    `    error: "${escapeYaml(attempt.error)}"`,
    `    tool: "${escapeYaml(attempt.tool)}"`,
    `    strategy: "${attempt.strategy}"`,
    `    attempts: ${attempt.attempts_total}`,
    `    resolved: ${attempt.resolved}`,
    `    action: "${escapeYaml(attempt.action)}"`,
  ].join('\n');

  if (existsSync(logPath)) {
    const existing = readFileSync(logPath, 'utf-8');
    writeFileSync(logPath, existing.trimEnd() + '\n' + entry + '\n');
  } else {
    const header = `# Recovery log for ${offerPath}\n# Auto-generated by recovery-handler.ts\nrecoveries:\n`;
    writeFileSync(logPath, header + entry + '\n');
  }
}

function escapeYaml(s: string): string {
  return s.replace(/"/g, '\\"').replace(/\n/g, '\\n');
}

// ==========================================
// Strategy 1: RETRY (exponential backoff)
// ==========================================

export function attemptRetry(ctx: RecoveryContext): RecoveryResult | null {
  const errorClass = classifyError(ctx.error);
  if (errorClass === 'PERMANENT') return null;
  if (detectCircular(ctx.attempt_history)) return null;

  const pastRetries = ctx.attempt_history.filter((a) => a.strategy === 'RETRY');
  if (pastRetries.length >= MAX_RETRIES) return null;

  const attemptNum = pastRetries.length + 1;
  const backoffMs = Math.min(1000 * Math.pow(2, pastRetries.length), MAX_BACKOFF_MS);

  // Synchronous sleep via execSync (no async needed)
  try {
    execSync(`sleep ${backoffMs / 1000}`, { stdio: 'ignore' });
  } catch {
    // sleep failed, continue anyway
  }

  const record: AttemptRecord = {
    strategy: 'RETRY',
    timestamp: new Date().toISOString(),
    success: false, // caller determines actual success
    details: `Retry attempt ${attemptNum}/${MAX_RETRIES} after ${backoffMs}ms backoff for ${ctx.tool}`,
  };

  ctx.attempt_history.push(record);

  // Return a "pending" result -- caller must re-invoke the tool and update
  return {
    resolved: false,
    strategy_used: 'RETRY',
    attempts: attemptNum,
    action_taken: `Waited ${backoffMs}ms, ready for retry attempt ${attemptNum}`,
    should_continue_pipeline: false,
  };
}

// ==========================================
// Strategy 2: ROLLBACK (via IDS)
// ==========================================

export function attemptRollback(ctx: RecoveryContext): RecoveryResult | null {
  try {
    // Dynamic import from IDS (same directory)
    const idsPath = join(dirname(new URL(import.meta.url).pathname), 'ids.ts');
    if (!existsSync(idsPath)) {
      return null;
    }

    // Read IDS decisions to find the last APPLIED decision for this offer
    const idsDir = join(HOME, '.claude', 'ids');
    const decisionsFile = join(idsDir, 'decisions.json');
    if (!existsSync(decisionsFile)) return null;

    const registry = JSON.parse(readFileSync(decisionsFile, 'utf-8'));
    const decisions = registry.decisions || [];

    // Find the most recent APPLIED decision related to this offer
    const relevant = decisions.filter((d: any) =>
      d.status === 'APPLIED' &&
      d.files_affected?.some((f: string) => f.includes(ctx.offer_path))
    );

    if (relevant.length === 0) return null;

    const lastDecision = relevant[relevant.length - 1];

    // Attempt rollback by restoring snapshots
    let restored = 0;
    for (const [filePath, content] of Object.entries(lastDecision.snapshots || {})) {
      try {
        if (content === null) {
          // File didn't exist before -- leave it (don't delete in recovery)
          continue;
        }
        const dir = dirname(filePath);
        if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
        writeFileSync(filePath, content as string);
        restored++;
      } catch {
        // Best effort per file
      }
    }

    // Mark as rolled back in IDS
    lastDecision.status = 'ROLLED_BACK';
    lastDecision.rolled_back_at = new Date().toISOString();
    registry.updated_at = new Date().toISOString();
    writeFileSync(decisionsFile, JSON.stringify(registry, null, 2));

    const record: AttemptRecord = {
      strategy: 'ROLLBACK',
      timestamp: new Date().toISOString(),
      success: restored > 0,
      details: `Rolled back IDS decision ${lastDecision.id}, restored ${restored} file(s)`,
    };
    ctx.attempt_history.push(record);

    return {
      resolved: restored > 0,
      strategy_used: 'ROLLBACK',
      attempts: ctx.attempt_history.filter((a) => a.strategy === 'ROLLBACK').length,
      action_taken: `Rolled back decision ${lastDecision.id} (${restored} files restored)`,
      should_continue_pipeline: restored > 0,
    };
  } catch (err) {
    const record: AttemptRecord = {
      strategy: 'ROLLBACK',
      timestamp: new Date().toISOString(),
      success: false,
      details: `Rollback failed: ${err}`,
    };
    ctx.attempt_history.push(record);
    return null;
  }
}

// ==========================================
// Strategy 3: SKIP
// ==========================================

export function attemptSkip(ctx: RecoveryContext): RecoveryResult | null {
  const skipReason = `Error in ${ctx.tool} during ${ctx.phase}: ${ctx.error.slice(0, 200)}`;
  const deliverableInfo = ctx.deliverable ? ` (deliverable: ${ctx.deliverable})` : '';

  const record: AttemptRecord = {
    strategy: 'SKIP',
    timestamp: new Date().toISOString(),
    success: true,
    details: `Skipped${deliverableInfo}. Reason: ${skipReason}`,
  };
  ctx.attempt_history.push(record);

  return {
    resolved: true,
    strategy_used: 'SKIP',
    attempts: 1,
    action_taken: `Skipped ${ctx.tool}${deliverableInfo}, flagged for human review`,
    should_continue_pipeline: true,
  };
}

// ==========================================
// Strategy 4: ESCALATE (via Decision Queue)
// ==========================================

export function attemptEscalate(ctx: RecoveryContext): RecoveryResult | null {
  try {
    // Write escalation to pending-decisions.yaml directly (avoid import of yaml pkg)
    const queuePath = join(ECOSYSTEM_ROOT, ctx.offer_path, 'pending-decisions.yaml');
    const queueDir = dirname(queuePath);
    if (!existsSync(queueDir)) mkdirSync(queueDir, { recursive: true });

    const ts = new Date().toISOString();
    const tsClean = ts.replace(/[-:T]/g, '').slice(0, 14);
    const rand = Math.random().toString(36).substring(2, 6);
    const decisionId = `dec-${tsClean}-${rand}`;

    const historyStr = ctx.attempt_history
      .map((a) => `${a.strategy}(${a.success ? 'ok' : 'fail'})`)
      .join(' -> ');

    const entry = [
      `  - id: "${decisionId}"`,
      `    offer_id: "${escapeYaml(ctx.offer_path)}"`,
      `    criterion_id: "recovery-escalation"`,
      `    type: "help_request"`,
      `    priority: "HIGH"`,
      `    status: "PENDING"`,
      `    blocking: true`,
      `    title: "Recovery failed: ${escapeYaml(ctx.tool)} in ${escapeYaml(ctx.phase)}"`,
      `    context: "Error: ${escapeYaml(ctx.error.slice(0, 300))}\\nHistory: ${escapeYaml(historyStr)}"`,
      `    created_at: "${ts}"`,
    ].join('\n');

    if (existsSync(queuePath)) {
      const existing = readFileSync(queuePath, 'utf-8');
      writeFileSync(queuePath, existing.trimEnd() + '\n' + entry + '\n');
    } else {
      const header = `version: "1.0.0"\nupdated_at: "${ts}"\ndecisions:\n`;
      writeFileSync(queuePath, header + entry + '\n');
    }

    const record: AttemptRecord = {
      strategy: 'ESCALATE',
      timestamp: ts,
      success: true,
      details: `Escalated to decision queue as ${decisionId}`,
    };
    ctx.attempt_history.push(record);

    return {
      resolved: false,
      strategy_used: 'ESCALATE',
      attempts: 1,
      action_taken: `Escalated to human decision queue (${decisionId}). Pipeline paused for this deliverable.`,
      should_continue_pipeline: false,
    };
  } catch (err) {
    const record: AttemptRecord = {
      strategy: 'ESCALATE',
      timestamp: new Date().toISOString(),
      success: false,
      details: `Escalation failed: ${err}`,
    };
    ctx.attempt_history.push(record);
    return null;
  }
}

// ==========================================
// Strategy 5: RECOVERY_WORKFLOW
// ==========================================

const RECOVERY_WORKFLOWS: Record<string, (ctx: RecoveryContext) => string | null> = {
  // MCP connection failures: restart MCP server
  'mcp_connection': (ctx) => {
    try {
      execSync('claude mcp list 2>/dev/null', { timeout: 5000, stdio: 'pipe' });
      return 'MCP server list refreshed; connection may recover on next call';
    } catch {
      return null;
    }
  },

  // Gate blocked: show what's missing
  'gate_blocked': (ctx) => {
    try {
      const statePath = join(ECOSYSTEM_ROOT, ctx.offer_path, 'helix-state.yaml');
      if (existsSync(statePath)) {
        const state = readFileSync(statePath, 'utf-8');
        return `Gate blocked. Current helix-state:\n${state.slice(0, 500)}`;
      }
      return 'Gate blocked but no helix-state.yaml found. Create it first.';
    } catch {
      return null;
    }
  },

  // Validation score too low: suggest rewrite
  'low_score': (_ctx) => {
    return 'Validation score below threshold. Deliverable should be rewritten with stronger specificity and VOC alignment.';
  },
};

export function attemptRecoveryWorkflow(ctx: RecoveryContext): RecoveryResult | null {
  // Determine which workflow matches the error
  let workflowKey: string | null = null;
  const errorLower = ctx.error.toLowerCase();

  if (/mcp.*connection|session.*not.*found/i.test(ctx.error)) {
    workflowKey = 'mcp_connection';
  } else if (/gate.*blocked/i.test(ctx.error)) {
    workflowKey = 'gate_blocked';
  } else if (/score.*\d|below.*threshold/i.test(ctx.error)) {
    workflowKey = 'low_score';
  }

  if (!workflowKey || !RECOVERY_WORKFLOWS[workflowKey]) return null;

  const result = RECOVERY_WORKFLOWS[workflowKey](ctx);
  if (!result) return null;

  const record: AttemptRecord = {
    strategy: 'RECOVERY_WORKFLOW',
    timestamp: new Date().toISOString(),
    success: true,
    details: `Executed workflow '${workflowKey}': ${result}`,
  };
  ctx.attempt_history.push(record);

  return {
    resolved: true,
    strategy_used: `RECOVERY_WORKFLOW:${workflowKey}`,
    attempts: 1,
    action_taken: result,
    should_continue_pipeline: true,
  };
}

// ==========================================
// Main Orchestrator
// ==========================================

/**
 * Execute the 5-strategy escalation ladder.
 * Tries each strategy in order: RETRY -> ROLLBACK -> SKIP -> ESCALATE -> RECOVERY_WORKFLOW.
 * Shortcuts based on error classification and circular detection.
 */
export function executeRecovery(ctx: RecoveryContext): RecoveryResult {
  const errorClass = classifyError(ctx.error);
  const isCircular = detectCircular(ctx.attempt_history);

  // Strategy order depends on error classification
  const strategies: Array<(ctx: RecoveryContext) => RecoveryResult | null> = [];

  if (errorClass === 'TRANSIENT' && !isCircular) {
    // Transient: try retry first, then escalation ladder
    strategies.push(attemptRetry, attemptRecoveryWorkflow, attemptRollback, attemptSkip, attemptEscalate);
  } else if (errorClass === 'PERMANENT') {
    // Permanent: skip retry entirely, try recovery workflow or rollback
    strategies.push(attemptRecoveryWorkflow, attemptRollback, attemptSkip, attemptEscalate);
  } else {
    // Circular (same error 3x): skip retry, go to rollback
    strategies.push(attemptRollback, attemptRecoveryWorkflow, attemptSkip, attemptEscalate);
  }

  let totalAttempts = ctx.attempt_history.length;

  for (const strategy of strategies) {
    const result = strategy(ctx);
    if (result) {
      totalAttempts = ctx.attempt_history.length;

      // Log the recovery attempt
      const lastRecord = ctx.attempt_history[ctx.attempt_history.length - 1];
      if (lastRecord) {
        logRecoveryAttempt(ctx.offer_path, {
          ...lastRecord,
          error: ctx.error,
          tool: ctx.tool,
          attempts_total: totalAttempts,
          resolved: result.resolved,
          action: result.action_taken,
        });
      }

      // If resolved or if it's an escalation (terminal), return
      if (result.resolved || result.strategy_used === 'ESCALATE') {
        return { ...result, attempts: totalAttempts };
      }

      // RETRY returns unresolved -- caller should re-invoke the tool
      if (result.strategy_used === 'RETRY') {
        return { ...result, attempts: totalAttempts };
      }
    }
  }

  // All strategies exhausted -- last resort escalation
  const fallback: RecoveryResult = {
    resolved: false,
    strategy_used: 'EXHAUSTED',
    attempts: ctx.attempt_history.length,
    action_taken: `All 5 recovery strategies exhausted for ${ctx.tool} in ${ctx.phase}. Manual intervention required.`,
    should_continue_pipeline: false,
  };

  logRecoveryAttempt(ctx.offer_path, {
    strategy: 'ESCALATE',
    timestamp: new Date().toISOString(),
    success: false,
    details: 'All strategies exhausted',
    error: ctx.error,
    tool: ctx.tool,
    attempts_total: ctx.attempt_history.length,
    resolved: false,
    action: fallback.action_taken,
  });

  return fallback;
}

// ==========================================
// Handoff Integration (v2.0 — Plan 6)
// ==========================================

/**
 * Recover a failed handoff task using the 5-strategy escalation ladder.
 * Called by the handoff-engine when a sub-task fails.
 *
 * Flow:
 *   handoff failTask → recoverHandoffTask → executeRecovery
 *   → if resolved: handoff skipTask or retry
 *   → if not: pipeline pauses
 */
export function recoverHandoffTask(params: {
  offer_path: string;
  deliverable: string;
  task_id: string;
  task_type: string;
  error: string;
  phase: string;
  attempt_history?: AttemptRecord[];
}): RecoveryResult & { recommendation: 'retry' | 'skip' | 'pause' } {
  const ctx: RecoveryContext = {
    error: params.error,
    tool: params.task_type,
    offer_path: params.offer_path,
    phase: params.phase,
    deliverable: params.deliverable,
    attempt_history: params.attempt_history || [],
  };

  const result = executeRecovery(ctx);

  // Map recovery result to handoff recommendation
  let recommendation: 'retry' | 'skip' | 'pause';
  if (result.strategy_used === 'RETRY' && !result.resolved) {
    recommendation = 'retry';
  } else if (result.resolved && result.should_continue_pipeline) {
    recommendation = 'skip';
  } else {
    recommendation = 'pause';
  }

  // Log to handoff events for visibility
  try {
    const logDir = join(HOME, '.claude/logs');
    if (!existsSync(logDir)) mkdirSync(logDir, { recursive: true });
    const event = {
      type: 'recovery_attempted',
      deliverable: params.deliverable,
      task_id: params.task_id,
      offer_path: params.offer_path,
      strategy: result.strategy_used,
      resolved: result.resolved,
      recommendation,
      timestamp: new Date().toISOString(),
    };
    appendFileSync(join(logDir, 'handoff-events.jsonl'), JSON.stringify(event) + '\n');
  } catch { /* best effort */ }

  return { ...result, recommendation };
}

/**
 * Quick check: is an error likely recoverable without human intervention?
 * Used by pipeline-executor to decide whether to auto-retry.
 */
export function isAutoRecoverable(error: string): boolean {
  const errorClass = classifyError(error);
  return errorClass === 'TRANSIENT';
}
